export const GET_DOGS = 'GET_DOGS';
export const GET_TEMPERAMENTS = 'GET_TEMPERAMENS';
export const NEW_DOG_BREED = 'NEW_DOG_BREED';
export const REMOVE_DOG_BREED = 'REMOVE_DOG_BREED';
export const GET_BY_NAME = 'GET_BY_NAME';
export const GET_DOG_DETAIL = 'GET_DOG_DETAIL';
export const CLEAR_DETAIL = 'CLEAR_DETAIL';


export const ORDER_BY_WEIGHT_MIN = 'ORDER_BY_WEIGHT_MIN';
export const ORDER_BY_WEIGHT_MAX = 'ORDER_BY_WEIGHT_MAX';
export const ORDER_FOR_NAME_ASC = 'ORDER_FOR_NAME_ASC';
export const ORDER_FOR_NAME_DESC = 'ORDER_FOR_NAME_DESC';
export const FILTER_BY_TEMPERAMENT = 'ORDER_BY_TEMPERAMENT';
export const FILTER_CREATE = 'FILTER_CREATE';
export const RESET = 'RESET';


export const FETCH_DOGS_REQUEST = 'FETCH_DOGS_REQUEST';
export const FETCH_DOGS_SUCCESS = 'FETCH_DOGS_SUCCESS';
export const FETCH_DOGS_FAILURE = 'FETCH_DOGS_FAILURE';


